version: '3'

services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}
    restart: always
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_USER: keycloak
      KC_DB_SCHEMA: public
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_HOSTNAME: ${HOST}
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      KC_PROXY: edge
    ports:
      - "9090:8080"
    depends_on:
      - keycloak-db
    networks:
      - keycloak-nw
      - host
    command: start --auto-build
  
  keycloak-db:
    container_name: keycloak-db
    image: postgres:13
    restart: always
    security_opt:
      - label:disable
    volumes:
      - ./container-data/db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - keycloak-nw
      
networks:
  keycloak-nw:
  host:
