version: '3'

services:
  keycloak-db:
    container_name: keycloak-db
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"